### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by ajuntapall** [felixchenfy/Realtime-Action-Recognition#23]
Hi, when I try to train (s4_train.py) my own train data (including yours) i get this error:
```
Traceback (most recent call last):
  File "src/s4_train.py", line 112, in <module>
    main()
  File "src/s4_train.py", line 99, in main
    model.train(tr_X, tr_Y)
  File "/home/suleyman/Desktop/COMPUTER VISION VIDEO CLASSIFICATION/Action-Recognition/src/../utils/lib_classifier.py", line 84, in train
    self.pca.fit(X)
  File "/home/suleyman/anaconda3/envs/comp_vision/lib/python3.7/site-packages/sklearn/decomposition/pca.py", line 341, in fit
    self._fit(X)
  File "/home/suleyman/anaconda3/envs/comp_vision/lib/python3.7/site-packages/sklearn/decomposition/pca.py", line 382, in _fit
    copy=self.copy)
  File "/home/suleyman/anaconda3/envs/comp_vision/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/suleyman/anaconda3/envs/comp_vision/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by felixchenfy** [comment]
@ajuntapall Hi, the error is due to a `NaN` in the training data (the feature vectors).   
Would you mind sending me the `skeletons_info.txt` generated from `s2_*.py` to my email `felixchenfy@gmail.com` or putting it here? It will help me a lot for debugging.  
Thank you very much!

**Comment by lktinh2018** [comment]
Dear felixchenfy,

I have a same issue too.
F.Y.I

Best regards,
Tinh Lam
[skeletons_info.txt](https://github.com/felixchenfy/Realtime-Action-Recognition/files/3857984/skeletons_info.txt)

**Comment by Salidor** [comment]
I have resolved the issue by replacing NaN:
```
def main():
    print("\nReading classes, features and labels ...")
    X = np.loadtxt(features_prc, dtype=float)
    Y = np.loadtxt(features_lbl_prc, dtype=int)
    col_mean = np.nanmean(X, axis=0)
    inds = np.where(np.isnan(X))
    X[inds] = np.take(col_mean, inds[1])
```

Idk if it's a proper solution but the recognition on test set works without a problem. Hope it helps.

**Comment by felixchenfy** [comment]
@Salidor Hi, it looks like a good solution! Thank you so much!

I will test your code today and then update the repo.

@lktinh2018 Thanks for your data! I will use it to test the code today.

**Comment by felixchenfy** [comment]
@Salidor @lktinh2018 Hi, I found the problem.
In `utils/lib_feature_proc.py`, I use the `body height` to normalize the skeleton. However, when the human is lying down, the height is zero, which causes the error.

So I changed the `body height` (y1-y2) to `body length` sqrt((x1-x2)**2 + (y1-y2)**2). The function after modification is shown below. The repo has been updated.  

```
    @staticmethod
    def get_body_height(x):
        ''' Compute height of the body, which is defined as:
            the distance between `neck` and `thigh`.
        '''
        x0, y0 = get_joint(x, NECK)

        # Get average thigh height
        x11, y11 = get_joint(x, L_THIGH)
        x12, y12 = get_joint(x, R_THIGH)
        if y11 == NaN and y12 == NaN:  # Invalid data
            return 1.0
        if y11 == NaN:
            x1, y1 = x12, y12
        elif y12 == NaN:
            x1, y1 = x11, y11
        else:
            x1, y1 = (x11 + x12) / 2, (y11 + y12) / 2

        # Get body height
        height = ((x0-x1)**2 + (y0-y1)**2)**(0.5)
        return height
```

@lktinh2018 By the way, I tried your data, and the test accuracy is only 80% to 85%. And then I tested using my web camera, and the result is very poor..... Just for your information ...

**Comment by DukeZacharia** [comment]
@felixchenfy Hello, I know it has been for some time since you haven't worked on this project but I want to ask if is there anyone who has achieved the lying down activity using a webcam.
