### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.neighbors.classification'

### ISSUE THREAD

**Issue by YePG** [felixchenfy/Realtime-Action-Recognition#76]
how to solve it?

**Comment by siabingtao** [comment]
I am facing the same issue too. Is anyone able to help? This happens when I am trying to run the s5_test.py script.

**Comment by siabingtao** [comment]
Hi, I managed to rectify it. I think that this happened because the installed version of scikit-learn was a newer one. 

I first uninstalled scikit-learn:
`pip uninstall scikit-learn
`
I then proceeded to install scikit-learn version 0.20.4:
`pip install scikit-learn==0.20.4`

**Comment by steve-95** [comment]
I have try pip install scikit-learn==0.20.4, and solved my problem ,thanks @siabingtao

**Comment by muyou111** [comment]
to install scikit-learn version 0.21.3 is OK

**Comment by TYang92677626** [comment]
I'm using scikit-learn1.4 version
Without downgrading the version, change sklearn.neighbors.classification in the trained_classifier.pickle of the training model to sklearn.neighbors._classification
Because scikit-learn has been underlined since version 0.22.x.
There are also several underlined ones:
Original: sklearn.tree.tree
Change to: sklearn.tree._classes (needs to be changed to classes here)
Original: sklearn.ensemble.forest
Change to: sklearn.ensemble._forest
Original: sklearn.preprocessing.label
Change to: sklearn.preprocessing._label
etc.

**Comment by steve-95** [comment]
thanks for your reply, I have get a mastor with the help of your work. good luck!



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 29, 2024 11:18 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [felixchenfy/Realtime-Action-Recognition] ModuleNotFoundError: Nomodule named 'sklearn.neighbors.classification' (Issue #76)




 
I'm using scikit-learn1.4 version
 Without downgrading the version, change sklearn.neighbors.classification in the trained_classifier.pickle of the training model to sklearn.neighbors._classification
 Because scikit-learn has been underlined since version 0.22.x.
 There are also several underlined ones:
 Original: sklearn.tree.tree
 Change to: sklearn.tree._classes (needs to be changed to classes here)
 Original: sklearn.ensemble.forest
 Change to: sklearn.ensemble._forest
 Original: sklearn.preprocessing.label
 Change to: sklearn.preprocessing._label
 etc.

**Comment by hieu2k2boss** [comment]
> Training_classifier.pickle

how to open file :"Training_classifier.pickle". I got this error when running "s5_test.py" .
Error:

Traceback (most recent call last):
  File "/content/drive/MyDrive/Realtime-Action-Recognition-master/src/s5_test.py", line 357, in <module>
    dict_id2label = multiperson_classifier.classify(
  File "/content/drive/MyDrive/Realtime-Action-Recognition-master/src/s5_test.py", line 219, in classify
    self.dict_id2clf[id] = self._create_classifier(id)
  File "/content/drive/MyDrive/Realtime-Action-Recognition-master/src/s5_test.py", line 201, in <lambda>
    self._create_classifier = lambda human_id: ClassifierOnlineTest(
  File "/content/drive/MyDrive/Realtime-Action-Recognition-master/src/../utils/lib_classifier.py", line 135, in __init__
    self.model = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '\xef'.

**Comment by xionzhen** [comment]
hello,I met a question about how to open file :"Training_classifier.pickle" and change the pickle.If I just open it in a directly way and change it to sklearn.neighbors._classification,will get the error of _pickle.UnpicklingError: invalid load key, '\xef'.
> I'm using scikit-learn1.4 version Without downgrading the version, change sklearn.neighbors.classification in the trained_classifier.pickle of the training model to sklearn.neighbors._classification Because scikit-learn has been underlined since version 0.22.x. There are also several underlined ones: Original: sklearn.tree.tree Change to: sklearn.tree._classes (needs to be changed to classes here) Original: sklearn.ensemble.forest Change to: sklearn.ensemble._forest Original: sklearn.preprocessing.label Change to: sklearn.preprocessing._label etc.
