### ISSUE TITLE
ModuleNotFoundError: No module named 'tf_pose'

### ISSUE THREAD

**Issue by Coder-Vishali** [felixchenfy/Realtime-Action-Recognition#81]
(har_venv) C:\Users\VISHALI\Desktop\Realtime-Action-Recognition-master>python src/s5_test.py --model_path model/trained_classifier.pickle --data_type video
 --data_path data_test/exercise.avi --output_folder output
Traceback (most recent call last):
  File "C:\Users\VISHALI\Desktop\Realtime-Action-Recognition-master\src\s5_test.py", line 57, in <module>
    from utils.lib_openpose import SkeletonDetector
  File "C:\Users\VISHALI\Desktop\Realtime-Action-Recognition-master\src/..\utils\lib_openpose.py", line 21, in <module>
    from tf_pose.networks import get_graph_path, model_wh
ModuleNotFoundError: No module named 'tf_pose'

**Comment by felixchenfy** [comment]
Sorry I don't have a quick answer now, since it's been many years since I worked on it.
Thanks for reporting the issue anyway

**Comment by StuartsFish** [comment]
> (har_venv) C:\Users\VISHALI\Desktop\Realtime-Action-Recognition-master>python src/s5_test.py --model_path model/trained_classifier.pickle --data_type video --data_path data_test/exercise.avi --output_folder output Traceback (most recent call last): File "C:\Users\VISHALI\Desktop\Realtime-Action-Recognition-master\src\s5_test.py", line 57, in from utils.lib_openpose import SkeletonDetector File "C:\Users\VISHALI\Desktop\Realtime-Action-Recognition-master\src/..\utils\lib_openpose.py", line 21, in from tf_pose.networks import get_graph_path, model_wh ModuleNotFoundError: No module named 'tf_pose'

You need to put the code of tf-pose-estimation into the "src\github".
Have a look at the "lib_openpose.py".
or 
Try to put the code"from tf_pose import..." behind the code "sys.append...."

**Comment by DukeZacharia** [comment]
i tried it out by using pip and it worked for me well.

pip install tf-pose
