### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'nn'

### ISSUE THREAD

**Issue by sch0722** [felixchenfy/Realtime-Action-Recognition#92]
`Traceback (most recent call last):
  File "s5_test.py", line 59, in <module>
    from   utils.lib_openpose import SkeletonDetector
  File "C:\Users\Hank\Downloads\action1\src/..\utils\lib_openpose.py", line 21, in <module>
    from tf_pose.networks import get_graph_path, model_wh
  File "C:\Users\Hank\Downloads\action1\utils/../src/githubs/tf-pose-estimation\tf_pose\__init__.py", line 5, in <module>
    from tf_pose.runner import infer, Estimator, get_estimator
  File "C:\Users\Hank\Downloads\action1\utils/../src/githubs/tf-pose-estimation\tf_pose\runner.py", line 7, in <module>
    from tf_pose import common
  File "C:\Users\Hank\Downloads\action1\utils/../src/githubs/tf-pose-estimation\tf_pose\common.py", line 10, in <module>
    activation_fn = tf.nn.relu
AttributeError: module 'tensorflow' has no attribute 'nn'`

Above message is my error while I run s5_test.py.
Did anyone get the same wrong?

**Comment by datnguyen-tien204** [comment]
I used tensorflow==1.15.0
          keras==2.1.6 
I fixed this error
